# Generated by Django 2.1.4 on 2018-12-22 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='victim',
            old_name='post',
            new_name='post1',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 18, 47, 26, 161117)),
        ),
    ]
