# Generated by Django 2.1.4 on 2018-12-22 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0003_auto_20181222_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 18, 58, 4, 668931)),
        ),
    ]
