# Generated by Django 2.1.4 on 2018-12-22 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0004_auto_20181222_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing_person',
            name='image',
            field=models.ImageField(default='images/non.png', upload_to='missing'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 2, 48, 32, 925068)),
        ),
    ]
