# Generated by Django 2.1.4 on 2018-12-23 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0006_auto_20181223_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 23, 17, 52, 972784)),
        ),
        migrations.AlterField(
            model_name='victim',
            name='image',
            field=models.ImageField(upload_to='victim'),
        ),
    ]
