# Generated by Django 2.1.4 on 2018-12-23 20:28

import datetime
from django.db import migrations, models
import find.models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0007_auto_20181223_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 23, 28, 59, 468685)),
        ),
        migrations.AlterField(
            model_name='victim',
            name='image',
            field=models.ImageField(default='images/non.png', upload_to=find.models.PathAndRename('E:\\python\\diplom2\\diplom2\\images/victim')),
        ),
    ]
