# Generated by Django 2.1.4 on 2018-12-23 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0008_auto_20181223_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing_person',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='missing', to='find.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 23, 53, 53, 797204)),
        ),
        migrations.AlterField(
            model_name='victim',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='find.Post'),
        ),
    ]
