# Generated by Django 2.1.4 on 2019-01-12 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0009_auto_20181223_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exactly', models.BooleanField(default=False)),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Missing_person')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Victim')),
            ],
        ),
        migrations.RenameField(
            model_name='relative',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 12, 18, 29, 43, 761950)),
        ),
    ]
