# Generated by Django 2.1.4 on 2019-01-13 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0010_auto_20190112_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 14, 1, 38, 305966)),
        ),
    ]
