# Generated by Django 2.1.4 on 2019-01-14 19:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0011_auto_20190113_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='missing_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_person', to='find.Missing_person'),
        ),
        migrations.AlterField(
            model_name='match',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_person', to='find.Victim'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 22, 40, 59, 65390)),
        ),
    ]
